steps:
# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/photo-challenge-bot:$COMMIT_SHA'
    - '.'

# Step 2: Push the built image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/photo-challenge-bot:$COMMIT_SHA'

# Defines the output image for the Cloud Run deployment stage
images:
- 'gcr.io/$PROJECT_ID/photo-challenge-bot:$COMMIT_SHA'

# Explicitly set the logging option to satisfy the requirement (c) in the error.
options:
  logging: CLOUD_LOGGING_ONLY
